### ISSUE TITLE
Detection issue

### ISSUE THREAD

**Issue by jaikishantulswani** [toufik-airane/leakin#2]
Hi @toufik-airane I send a message via calendly regarding an issue because at that time the issue tab was not available. I have found that leakin detecting the leaks from the leaky-repo but not able to found even a single leak from https://github.com/bugbaba/test4truffleHog

**Comment by jaikishantulswani** [comment]
@toufik-airane forgot to check that the issue have been solved now it is working on test4trufflehog repo too.

**Comment by toufik-airane** [comment]
Dear @jaikishantulswani,

Thank you for your message.
I've taken clear actions to fix the issue and make myself more ease to contact.

If you have any more feedback, feel free to ping me.

Regards. 👋
